### ISSUE TITLE
Implement Joy Plots

### ISSUE THREAD

**Issue by cxhernandez** [msmexplorer/msmexplorer#101]
They're trendy and a good option for discrete time-series analysis of distributions. I imagine this would be nice to look at features evolving along a transition pathway.

Also fairly simple to implement:

```python
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

# Create the data
rs = np.random.RandomState(42)
x = rs.randn(500)
g = np.tile(list("ABCDEFGHIJ"), 50)
df = pd.DataFrame(dict(x=x, g=g))
m = df.g.map(ord)
df["x"] += m

# Initialize the FacetGrid object
pal = sns.cubehelix_palette(10, rot=-.25, light=.7)
g = sns.FacetGrid(df, row="g", hue="g", aspect=12, size=.5, palette=pal)

# Draw the densities in a few steps
g.map(sns.kdeplot, "x", clip_on=False, shade=True, alpha=1, lw=1.5, bw=.2)
g.map(sns.kdeplot, "x", clip_on=False, color="w", lw=2, bw=.2)
g.map(plt.axhline, y=0, lw=2, clip_on=False)

# Define and use a simple function to label the plot in axes coordinates
def label(x, color, label):
    ax = plt.gca()
    ax.text(0, .2, label, fontweight="bold", color=color, 
            ha="left", va="center", transform=ax.transAxes)

g.map(label, "x")

# Set the subplots to overlap
g.fig.subplots_adjust(hspace=-.25)

# Remove axes details that don't play will with overlap
g.set_titles("")
g.set(yticks=[])
g.despine(bottom=True, left=True)
```

![image](https://user-images.githubusercontent.com/5142365/28548482-15f23986-7089-11e7-9891-b29ad1b14777.png)

**Comment by mpharrigan** [comment]
why is this called a joy plot

**Comment by cxhernandez** [comment]
From [ggjoy](https://github.com/clauswilke/ggjoy):

>  The name "joyplot" was proposed by Jenny Bryan on Twitter on April 24, 2017, in reference to the iconic cover art for Joy Division's album Unknown Pleasures.

**Comment by mpharrigan** [comment]
:eyeroll:

**Comment by cxhernandez** [comment]
Not a fan of Joy, I see.

**Comment by msultan** [comment]
:man_facepalming:

**Comment by cxhernandez** [comment]
Thoughts on this?

![image](https://user-images.githubusercontent.com/5142365/28694939-19776a18-72e1-11e7-9080-b0176ad89e8c.png)

The idea is to have many features in the same plot over several states. @msultan thinks it's a little busy though.

**Comment by msultan** [comment]
Something like this could be might be more clearer? My fear is that people tend to interpret a single axis as representing the same variable. 
![image](https://user-images.githubusercontent.com/3597136/28696909-6410a380-72ed-11e7-83cd-8b10d6c0ed7a.png)

**Comment by cxhernandez** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/5142365/28739585-f7d21040-73b0-11e7-8a0c-8a58485c46aa.png)

**Comment by cxhernandez** [comment]
done in #102
