### ISSUE TITLE
AttributeError: module 'msmexplorer' has no attribute 'plot_implied_timescales'

### ISSUE THREAD

**Issue by mkhoshle** [msmexplorer/msmexplorer#111]
Hi,
I am trying to plot Implied time_scales using msme.plot_implied_timescales, but I am getting the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-68-73601e52d38e> in <module>()
      1 colors = ['pomegranate', 'beryl', 'tarragon', 'rawdenim', 'carbon']
----> 2 msme.plot_implied_timescales(msm_objs, color_palette=colors, 
      3                              xlabel='Lag time (frames)',
      4                              ylabel='Implied Timescales ($ns$)')

AttributeError: module 'msmexplorer' has no attribute 'plot_implied_timescales'
```
Even the following [example](http://msmbuilder.org/msmexplorer/development/examples/plot_implied_timescales.html) gives the same error. I think I have the updated package, but is there any other attribute for this?

**Comment by cxhernandez** [comment]
You need to install the development version for this function. See [here](http://msmbuilder.org/msmexplorer/development/installing.html#installing-and-getting-started) for details on how to install using `pip`.

**Comment by mkhoshle** [comment]
Ok, working now! Thank you!

**Comment by cxhernandez** [comment]
Great!
