### ISSUE TITLE
~~CLI or Webserver (or both)?~~ API

### ISSUE THREAD

**Issue by cxhernandez** [msmexplorer/msmexplorer#3]
Would it be more useful to have a CLI or local HTTP server for data exploration and plot generation. I imagine people would want both, but which is a higher priority?

cc @msultan @mpharrigan

**Comment by msultan** [comment]
api + ipython notebooks would be plenty enough to start with. People tend to fiddle with their plots a lot so we should start with the simple things.

**Comment by mpharrigan** [comment]
> People tend to fiddle with their plots a lot 

This was my motivation for the plotting elements of https://github.com/msmbuilder/msmbuilder/pull/768 wherein it generates boilerplate / an example plot but you can fiddle using your extant knowledge of matplotlib/seaborn/whatever. For an API based solution, you need to be so careful about allowing customizability where people need it and hiding it where they don't.

**Comment by cxhernandez** [comment]
I agree. I'm gonna focus on the API here and then work on [msmreport](https://github.com/cxhernandez/msmreport/tree/init) for fully automated plotting from Osprey projects
