### ISSUE TITLE
Path vertices problem in Chord Diagram

### ISSUE THREAD

**Issue by cing** [msmexplorer/msmexplorer#37]
Seems to me that the destination vertex for the chord plot is incorrect. My 
plot here has a line connecting labels "1" and "2" when I was hoping for "1" and "5"?

```
import msmexplorer as msme

d=np.zeros([10,10])
d[1,5]=1.0
labels=range(10)
msme.plot_chord(d, labels=labels)
```
<img width="275" alt="screen shot 2016-09-08 at 2 58 15 pm" src="https://cloud.githubusercontent.com/assets/116655/18362674/bcdd9e44-75d4-11e6-8d5b-169592a47fb2.png">

**Comment by cxhernandez** [comment]
Good catch! I'll look into it now.

**Comment by cxhernandez** [comment]
done in https://github.com/msmexplorer/msmexplorer/pull/38

**Comment by cing** [comment]
Awesome, thanks!
