### ISSUE TITLE
`plot_trace` gets mad if only `ax` is provided

### ISSUE THREAD

**Issue by mpharrigan** [msmexplorer/msmexplorer#52]
If you supply `ax` but not `side_ax`, it gives a confusing error message. 

I would advocate for a convention where each function takes a parameter named `ax`, and it it is not `None`, then the function won't do any funny business with subplots.

Non-power users' use case: Don't mess with axes objects; msmexplorer makes everything look good by default

Power-users: maybe you want to reshape a plot, overlay something else on top, have subplots arranged in a different way, etc. Pass an axes to the `ax` parameter and msmexplorer will step off a bit

**Comment by cxhernandez** [comment]
So for this particular case, throw a `ValueError` if one is provided but not the other?

**Comment by cxhernandez** [comment]
Or should ax be a tuple?

**Comment by mpharrigan** [comment]
PR incoming for my idea

**Comment by cxhernandez** [comment]
cc @msultan since we ran into this issue yesterday

**Comment by cxhernandez** [comment]
done in #54
