### ISSUE TITLE
Do we really want seaborn.apionly?

### ISSUE THREAD

**Issue by mpharrigan** [msmexplorer/msmexplorer#53]
The plots look better if you import seaborn proper

**Comment by cxhernandez** [comment]
Didn't want to force the user to use seaborn defaults.

**Comment by mpharrigan** [comment]
It looks like they get applied if you use any of the seaborn functions. Specifically, I'm looking at plot_trace. If you just plot the trace (and not the histogram (see forthcoming PR)) the axes has an ugly border. Once you `sns.kdeplot`, it applies the seaborn stylings anyways

**Comment by cxhernandez** [comment]
Ah. That's weird that `seaborn.apionly.kdeplot` still applies the styling. Then maybe we should force it.

**Comment by mpharrigan** [comment]
I'd actually be slightly in favor of enforcing it anyways. The goal of this package is to make nice plots, and seaborn helps do that. It's very not-overbearing; people with strong opinions can work around it. We shouldn't spend developer time worrying about people who don't like the seaborn changes

**Comment by cxhernandez** [comment]
done in #62
