### ISSUE TITLE
Conda build issues

### ISSUE THREAD

**Issue by jchodera** [msmexplorer/msmexplorer#68]
Can you guys take a look at the upstream PyQT4 dependency? This seems to be missing for py3.x builds on `omnia`:
https://travis-ci.org/omnia-md/conda-recipes/jobs/172303670#L685-L717

I'm going to have to disable py3.x builds if we can't find a solution or else our PRs are going to perpetually fail.

**Comment by cxhernandez** [comment]
Any chance https://github.com/msmexplorer/msmexplorer/pull/57 might solve this?

**Comment by cxhernandez** [comment]
Appears to be a larger issue with Anaconda's matplotlib build: https://github.com/ContinuumIO/anaconda-issues/issues/1068

**Comment by jchodera** [comment]
https://www.traviscistatus.com/incidents/lp492hx0z1my

**Comment by mpharrigan** [comment]
Do you really need to import matplotlib to build the conda package? Omnia conda recipes typically don't run any tests

**Comment by jchodera** [comment]
cc: https://github.com/omnia-md/conda-recipes/pull/627

**Comment by mpharrigan** [comment]
👍
