### ISSUE TITLE
add implied timescales plot vs lag time

### ISSUE THREAD

**Issue by jeiros** [msmexplorer/msmexplorer#89]
I'd be interested in having an implied timescales plot API. Do you have in mind adding it? I could give it a go.

**Comment by cxhernandez** [comment]
What did you have in mind for the command arguments? A list of `msmbuilder.msm.MarkovStateModel` objects perhaps?

**Comment by jeiros** [comment]
Yes, that's what I thought. A list of msm objects each calculated at a different lag time.

Another option would be passing a list of lag times, with an extra argument for a clustered trajectories list (a list of np.arrays). But that would mean that the actual computation of the msms is done inside the function (which I don't know if it's consistent with the rest of your API, from the looks of it it's all basically plotting functions without too much computation, so you leave the actual computation of msms to the user and msmbuilder).

**Comment by cxhernandez** [comment]
done in #90
