### ISSUE TITLE
Add implied timescales plot to notebook

### ISSUE THREAD

**Issue by cxhernandez** [msmexplorer/msmexplorer#96]
This is a pretty key plot to showcase.

**Comment by jeiros** [comment]
I could to this (you mean the Implied Timescales plot I added?) Where would it go?

**Comment by cxhernandez** [comment]
@jeiros: That would be much appreciated! You could edit this [notebook](https://github.com/msmexplorer/msmexplorer/blob/master/notebooks/Fs-Peptide-Example.ipynb) and, perhaps, add it to the "MSM Construction" example?

**Comment by jeiros** [comment]
Hi, I'm doing this right now. One thing though, in the `msme.plot_timescales` plot, no interconversion is made between the unit of timescales coming from `msm.timescales_`, right? The ylabel says nanosecons but these are actually frames, so should change to ns according to the timestep of the trajectories?

**Comment by cxhernandez** [comment]
done in #107
